version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devlife
      MYSQL_DATABASE: devlife
      MYSQL_USER: devlife
      MYSQL_PASSWORD: devlife
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
